version: "3.8"
services:
  backend:
    image: ${BACKEND_IMAGE} # Dynamically set from Jenkins pipeline
    container_name: spring-boot-app-2
    ports:
      - "8080:8080" # Map backend container port to host port 8080
    volumes:
      - weather-cache-volume:/app
    networks:
      - weather-app-network # Add service to custom network

volumes:
  weather-cache-volume: # Volume for backend data persistence

networks:
  weather-app-network:
    driver: bridge # Explicitly defining a custom bridge network
